#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer. Note that the ron color scheme is default in Vim in dark
    # terminals and must be used in order to have transparent backgrounds.
    colorscheme = "ron"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors. Needs to be false to enable transparent backgrounds.
    enable_guicolors = false

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    # Fix numbering
    relativenumber = false
    # For tabbing
    expand_tab = true
    default_indent = 4

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "cycle"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
  name = "lsp"
  filetypes = [
      "javascript",
      "html",
      "css",
      "python",
      "sh",
      "go"
  ]

[[layers]]
    name = 'colorscheme'

[[layers]]
    name = "lang#python"
    enable_typeinfo = true

[[layers]]
    name = "lang#java"

[[layers]]
    name = "lang#c"
    clang_executable = "/usr/bin/clang"
    [layer.clang_std]
        c = "c11"

[[layers]]
    name = "lang#extra"

[[layers]]
    name = "lang#go"

[[layers]]
    name = "lang#html"

[[layers]]
    name = "lang#markdown"
    listItemIndent = "tab"

[[layers]]
    name = "lang#sh"
